stages:
  - build
  - test
  - deploy

building_app:
  stage: build
  script:
    - "npm install"
    - "npm run build"

testing_app:
  stage: test
  script:
    - "npm install"
    - "npm run test"

deploy_to_server:
  stage: deploy
  script:
    - "npm install"
    - "npm run build"
    - "~/copy_files.sh"

